#:kivy 1.9.0
<Widget>:
    font_name: '../gui/fonts/WenQuanYi_Micro_Hei.ttf'

<Record>:
    size_hint_y: None
    height: '30dp'
    width: '100dp'

    canvas.before:
        Color:
            rgb: 0.2, 0.2, 0.2
        Rectangle:
            pos: self.pos
            size: self.size

<TableHeader>
    size_hint_y: None
    height: '30dp'
    width: '100dp'

    canvas.before:
        Color:
            rgb: 0.5, 0.5, 0.5
        Rectangle:
            pos: self.pos
            size: self.size

<CustomTable>:
    anchor_x: 'center'
    anchor_y: 'center'
    ScrollView:
        MyGrid:
            id: Tables
            cols: self.cols
            rows:self.rows
            size_hint_y: None
            height: self.minimum_height
            spacing: '1dp'