<PlayerRecord>:
    size_hint_y: None
    height: '30dp'
    width: '100dp'

    canvas.before:
        Color:
            rgb: 0.2, 0.2, 0.2
        Rectangle:
            pos: self.pos
            size: self.size

<TableHeader>
    size_hint_y: None
    height: '30dp'
    width: '100dp'

    canvas.before:
        Color:
            rgb: 0.5, 0.5, 0.5
        Rectangle:
            pos: self.pos
            size: self.size

AnchorLayout:
    anchor_x: 'center'
    anchor_y: 'center'

    ScrollView:
        size_hint_y: None
        height: '200dp'

        MyGrid:
            cols: 3
            size_hint_y: None
            height: self.minimum_height
            spacing: '1dp'