#!/bin/bash
./get_tick_data.py 0 &
./get_tick_data.py 1 &
./get_tick_data.py 2 &
./get_tick_data.py 3 &
./get_tick_data.py 4 &
./get_tick_data.py 5 &
./get_tick_data.py 6 &
./get_tick_data.py 7 &
#./get_tick_data.py 8 &
#./get_tick_data.py 9 &
#./get_tick_data.py 10 &
#./get_tick_data.py 11 &
#./get_tick_data.py 12 &
#./get_tick_data.py 13 &
#./get_tick_data.py 14 &
#./get_tick_data.py 15 &
#./get_tick_data.py 16 &
#./get_tick_data.py 17 &
#./get_tick_data.py 18 &
#./get_tick_data.py 19 &
#./get_tick_data.py 21 &
#./get_tick_data.py 22 &
#./get_tick_data.py 23 &
#./get_tick_data.py 24 &
#./get_tick_data.py 25 &
#./get_tick_data.py 26 &
#./get_tick_data.py 27 &
#./get_tick_data.py 28 &
#./get_tick_data.py 29 &
#./get_tick_data.py 30 &
#./get_tick_data.py 31 &