import os
import pickle

import pandas as pd
import multiprocessing as mp
from configs.path import DIRs
from tools.io import logging


class ConditionalStatisticsHdl:
    def __init__(self, params, data_folder, name):
        self.params = params
        self.probability_dict = {}
        self.base_dir = self._validate_input_path(data_folder)
        self.symbol_list = os.listdir(self.base_dir)
        self.data = None
        self.name = name

    @staticmethod
    def _validate_input_path(p):
        if os.path.isfile(p):
            return p
        elif p.split('/')[0] in os.listdir(DIRs.get("QA")):
            if os.path.exists(DIRs.get("QA") + '/' + p):
                return DIRs.get("QA") + '/' + p

        elif p.split('/')[0] in os.listdir(DIRs.get("DATA_ROOT")):
            if os.path.exists(DIRs.get("DATA_ROOT") + '/' + p):
                return DIRs.get("DATA_ROOT") + '/' + p
        else:
            return DIRs.get("QA") + '/' + p

    def generate_path_list(self):
        path_list = []
        for s in self.symbol_list:
            path_list.append(os.path.join(self.base_dir, s))
        return path_list

    def statistic(self):
        path_list = self.generate_path_list()
        tmp = []
        pool = mp.Pool()
        for i in path_list:
            pool.apply_async(counting, args=(i, self.params), callback=tmp.append)
        pool.close()
        pool.join()
        ks = tmp[0].keys()
        result = {k: 0 for k in ks}
        division = len(tmp) if len(tmp) != 0 else 1
        for l in tmp:
            for p in l.keys():
                result[p] += l[p]
        for k in ks:
            result[k] /= division
        self.probability_dict = result
        print(result)
        self.save()

    def save(self):
        with open('%s' % (os.path.join(DIRs.get("MODEL"), "%s.pickle" % self.name)), 'wb') as f:
            pickle.dump(self.probability_dict, f, -1)

    def load(self):
        try:
            with open('%s' % (os.path.join(DIRs.get("MODEL"), "%s.pickle" % self.name)), 'rb') as f:
                self.probability_dict = pickle.load(f)
        except FileNotFoundError:
            self.probability_dict = {}


def counting(path, params):
    result = {}
    param_list = params.split(" ")
    d = pd.read_csv(path)
    for p in param_list:
        data = d.copy()
        targets = p.split("|")[0].split(",")
        given = p.split("|")[1].split(",")
        for g in given:
            data = data[data[g] == True]
        given_cnt = len(data.index)
        for t in targets:
            data = data[data[t] == True]
        target_cnt = len(data.index)
        result[p] = target_cnt / given_cnt if given_cnt != 0 else 0
    logging("Counting", "applied_%s" % path.split("/")[-1].split(".")[0])

    return result


if __name__ == '__main__':
    c = ConditionalStatisticsHdl(
        "QUICK_BUYPOINT|CROSS QUICK_BUYPOINT|TSHAPE QUICK_BUYPOINT|REVERSETSHAPE QUICK_BUYPOINT|ONESHAPE QUICK_BUYPOINT|JUMPHIGHOPEN QUICK_BUYPOINT|JUMPLOWOPEN QUICK_BUYPOINT|MORNINGCROSS QUICK_BUYPOINT|MORNINGSTAR QUICK_BUYPOINT|FRIENDLYFIRE QUICK_BUYPOINT|HOPEOFDAWN QUICK_BUYPOINT|RAISINGSUN QUICK_BUYPOINT|REVERSEHAMMER QUICK_BUYPOINT|HAMMER QUICK_BUYPOINT|FLATFLOOR QUICK_BUYPOINT|CONTINUETHREEJUMPYIN QUICK_BUYPOINT|TRIPLEREDARMY QUICK_BUYPOINT|UPWARDTWOSTARS QUICK_BUYPOINT|JUMPUPWARD QUICK_BUYPOINT|JUMPUPWARDYANG QUICK_BUYPOINT|JUMPDOWNWARDTHREESTARS QUICK_BUYPOINT|TRIPLEUPWARDS QUICK_BUYPOINT|TWOREDONEBLACK QUICK_BUYPOINT|TWILICROSS QUICK_BUYPOINT|TWILISTAR QUICK_BUYPOINT|FRIENDLYPUSHBACK QUICK_BUYPOINT|INCOMINGCLOUDS QUICK_BUYPOINT|HEAVYRAIN QUICK_BUYPOINT|SHOOTINGSTAR QUICK_BUYPOINT|HANGWIRE QUICK_BUYPOINT|FLATROOF QUICK_BUYPOINT|DOUBLECROWS QUICK_BUYPOINT|TRIPLECROWS QUICK_BUYPOINT|HEADSFEETYIN QUICK_BUYPOINT|HEADSFEETYANG QUICK_BUYPOINT|DOWNWARDCOVER QUICK_BUYPOINT|TRIPLEBLKARMY QUICK_BUYPOINT|MILDDOWNWARDS QUICK_BUYPOINT|RUSHINGAWAY QUICK_BUYPOINT|DOWNWARDTRIPLESTARS QUICK_BUYPOINT|DOWNWARDTRIPLESWANS QUICK_BUYPOINT|TRIPLEDOWNWARDSYANG QUICK_BUYPOINT|JUMPHIGHTRIPLEYANG QUICK_BUYPOINT|UPWARDRESISTENCE QUICK_BUYPOINT|UPWARDPAUSE QUICK_BUYPOINT|LAMPYANG QUICK_BUYPOINT|BLKREDBLK QUICK_BUYPOINT|LONGCROSS QUICK_BUYPOINT|PROPELLER QUICK_BUYPOINT|EOFUPWARD QUICK_BUYPOINT|EOFDOWNWARD QUICK_BUYPOINT|PREGNANTYANG QUICK_BUYPOINT|PREGNANTYIN QUICK_BUYPOINT|MAALIGNUPWARD QUICK_BUYPOINT|MAALIGNDOWNWARD QUICK_BUYPOINT|GOLDCROSS510 QUICK_BUYPOINT|GOLDCROSS520 QUICK_BUYPOINT|GOLDCROSS1020 QUICK_BUYPOINT|LOSECROSS510 QUICK_BUYPOINT|LOSECROSS520 QUICK_BUYPOINT|LOSECROSS1020 QUICK_BUYPOINT|GOLDVALLEY QUICK_BUYPOINT|LOSEVALLEY QUICK_BUYPOINT|DRAGONOUT QUICK_BUYPOINT|LOSEEVERYTHING",
        "merged", "cond_buy")
    c.statistic()

    d = ConditionalStatisticsHdl(
        "QUICK_SELLPOINT|CROSS QUICK_SELLPOINT|TSHAPE QUICK_SELLPOINT|REVERSETSHAPE QUICK_SELLPOINT|ONESHAPE QUICK_SELLPOINT|JUMPHIGHOPEN QUICK_SELLPOINT|JUMPLOWOPEN QUICK_SELLPOINT|MORNINGCROSS QUICK_SELLPOINT|MORNINGSTAR QUICK_SELLPOINT|FRIENDLYFIRE QUICK_SELLPOINT|HOPEOFDAWN QUICK_SELLPOINT|RAISINGSUN QUICK_SELLPOINT|REVERSEHAMMER QUICK_SELLPOINT|HAMMER QUICK_SELLPOINT|FLATFLOOR QUICK_SELLPOINT|CONTINUETHREEJUMPYIN QUICK_SELLPOINT|TRIPLEREDARMY QUICK_SELLPOINT|UPWARDTWOSTARS QUICK_SELLPOINT|JUMPUPWARD QUICK_SELLPOINT|JUMPUPWARDYANG QUICK_SELLPOINT|JUMPDOWNWARDTHREESTARS QUICK_SELLPOINT|TRIPLEUPWARDS QUICK_SELLPOINT|TWOREDONEBLACK QUICK_SELLPOINT|TWILICROSS QUICK_SELLPOINT|TWILISTAR QUICK_SELLPOINT|FRIENDLYPUSHBACK QUICK_SELLPOINT|INCOMINGCLOUDS QUICK_SELLPOINT|HEAVYRAIN QUICK_SELLPOINT|SHOOTINGSTAR QUICK_SELLPOINT|HANGWIRE QUICK_SELLPOINT|FLATROOF QUICK_SELLPOINT|DOUBLECROWS QUICK_SELLPOINT|TRIPLECROWS QUICK_SELLPOINT|HEADSFEETYIN QUICK_SELLPOINT|HEADSFEETYANG QUICK_SELLPOINT|DOWNWARDCOVER QUICK_SELLPOINT|TRIPLEBLKARMY QUICK_SELLPOINT|MILDDOWNWARDS QUICK_SELLPOINT|RUSHINGAWAY QUICK_SELLPOINT|DOWNWARDTRIPLESTARS QUICK_SELLPOINT|DOWNWARDTRIPLESWANS QUICK_SELLPOINT|TRIPLEDOWNWARDSYANG QUICK_SELLPOINT|JUMPHIGHTRIPLEYANG QUICK_SELLPOINT|UPWARDRESISTENCE QUICK_SELLPOINT|UPWARDPAUSE QUICK_SELLPOINT|LAMPYANG QUICK_SELLPOINT|BLKREDBLK QUICK_SELLPOINT|LONGCROSS QUICK_SELLPOINT|PROPELLER QUICK_SELLPOINT|EOFUPWARD QUICK_SELLPOINT|EOFDOWNWARD QUICK_SELLPOINT|PREGNANTYANG QUICK_SELLPOINT|PREGNANTYIN QUICK_SELLPOINT|MAALIGNUPWARD QUICK_SELLPOINT|MAALIGNDOWNWARD QUICK_SELLPOINT|GOLDCROSS510 QUICK_SELLPOINT|GOLDCROSS520 QUICK_SELLPOINT|GOLDCROSS1020 QUICK_SELLPOINT|LOSECROSS510 QUICK_SELLPOINT|LOSECROSS520 QUICK_SELLPOINT|LOSECROSS1020 QUICK_SELLPOINT|GOLDVALLEY QUICK_SELLPOINT|LOSEVALLEY QUICK_SELLPOINT|DRAGONOUT QUICK_SELLPOINT|LOSEEVERYTHING",
        "merged", 'cond_sell')
    d.statistic()
